//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiDisplayTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiDisplayTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer: Mehdi Dimyadi
        ///Description: MultiDisplayTool - A utility for managing multiple displays.
        ///
        ///Copyright © 2024 Mehdi Dimyadi.
        /// </summary>
        internal static string aboutDescription {
            get {
                return ResourceManager.GetString("aboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MultiDisplayTool.
        /// </summary>
        internal static string aboutFormTitle {
            get {
                return ResourceManager.GetString("aboutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub: @mehdimyadi.
        /// </summary>
        internal static string aboutGitHubLink {
            get {
                return ResourceManager.GetString("aboutGitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string aboutOKButton {
            get {
                return ResourceManager.GetString("aboutOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Startup.
        /// </summary>
        internal static string mainFormAddToStartup {
            get {
                return ResourceManager.GetString("mainFormAddToStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDisplayTool: Click to manage display settings..
        /// </summary>
        internal static string mainFormBalloonTipText {
            get {
                return ResourceManager.GetString("mainFormBalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto Move.
        /// </summary>
        internal static string mainFormDisableAutoMove {
            get {
                return ResourceManager.GetString("mainFormDisableAutoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto SetPrimary Display.
        /// </summary>
        internal static string mainFormDisableAutoSetPrimary {
            get {
                return ResourceManager.GetString("mainFormDisableAutoSetPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Move.
        /// </summary>
        internal static string mainFormEnableAutoMove {
            get {
                return ResourceManager.GetString("mainFormEnableAutoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto SetPrimary Display.
        /// </summary>
        internal static string mainFormEnableAutoSetPrimary {
            get {
                return ResourceManager.GetString("mainFormEnableAutoSetPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings: {0}.
        /// </summary>
        internal static string mainFormErrorLoadingSettings {
            get {
                return ResourceManager.GetString("mainFormErrorLoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings: {0}.
        /// </summary>
        internal static string mainFormErrorSavingSettings {
            get {
                return ResourceManager.GetString("mainFormErrorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all windows to the next monitor.
        /// </summary>
        internal static string mainFormMoveWindowsToNext {
            get {
                return ResourceManager.GetString("mainFormMoveWindowsToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all windows to the primary monitor.
        /// </summary>
        internal static string mainFormMoveWindowsToPrimary {
            get {
                return ResourceManager.GetString("mainFormMoveWindowsToPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Startup.
        /// </summary>
        internal static string mainFormRemoveFromStartup {
            get {
                return ResourceManager.GetString("mainFormRemoveFromStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set next display as primary.
        /// </summary>
        internal static string mainFormSetPrimaryDisplay {
            get {
                return ResourceManager.GetString("mainFormSetPrimaryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDisplayTool.
        /// </summary>
        internal static string mainFormTitle {
            get {
                return ResourceManager.GetString("mainFormTitle", resourceCulture);
            }
        }
    }
}
